# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-23 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes_citas',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('id_alumno', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('id_maestro', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('tipo', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=45)),
                ('comentarios', models.CharField(max_length=225)),
            ],
        ),
    ]
