# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_tuto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('nombres', models.CharField(max_length=45)),
                ('ap_paterno', models.CharField(max_length=45)),
                ('ap_materno', models.CharField(max_length=45)),
                ('matricula', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id_maestro', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('num_empleado', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('nombres', models.CharField(max_length=45)),
                ('ap_paterno', models.CharField(max_length=45)),
                ('ap_materno', models.CharField(max_length=45)),
                ('carrera', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudes_citas',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_tuto.Alumnos'),
        ),
    ]
