# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_tuto', '0002_auto_20180424_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_citas',
            name='id_maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_tuto.Maestros'),
        ),
    ]
