# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_tuto', '0003_auto_20180424_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_citas',
            name='comentarios',
            field=models.TextField(),
        ),
    ]
