# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_tuto', '0004_auto_20180424_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_citas',
            name='comentarios',
            field=models.CharField(max_length=225),
        ),
    ]
