# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_tuto', '0005_auto_20180424_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_citas',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumnos'),
        ),
        migrations.AlterField(
            model_name='solicitudes_citas',
            name='id_maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.Maestros'),
        ),
        migrations.DeleteModel(
            name='Alumnos',
        ),
        migrations.DeleteModel(
            name='Maestros',
        ),
    ]
