# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_tuto', '0006_auto_20180425_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes_citas',
            old_name='id_alumno',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='solicitudes_citas',
            old_name='id_maestro',
            new_name='num_empleado',
        ),
    ]
