# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestros',
            fields=[
                ('id_maestro', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('num_empleado', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('nombres', models.CharField(max_length=45)),
                ('ap_paterno', models.CharField(max_length=45)),
                ('ap_materno', models.CharField(max_length=45)),
                ('carrera', models.CharField(max_length=15)),
            ],
        ),
    ]
