# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 05:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosSiita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('usuario', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
