# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 23:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20180415_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='idcarrera',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='idpersona',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='idplan',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
