# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 20:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumnos_idplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='id_alumno',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
