# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
    ]
