# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 20:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0002_auto_20180426_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('edificio', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cuatrimestres',
            fields=[
                ('id_cuatrimestre', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('id_cuatrimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Cuatrimestres')),
                ('id_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.Maestros')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('dia', models.CharField(max_length=10)),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name=['%I:%H %p'])),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name=['%I:%H %p'])),
                ('id_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Aulas')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('nombre', models.CharField(max_length=25)),
                ('clave', models.CharField(max_length=25)),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Carreras')),
            ],
        ),
        migrations.AddField(
            model_name='grupos',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Materias'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Planes'),
        ),
    ]
