# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_grupos_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='nombre',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
