# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-27 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_aulas_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='id_carrera',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='id_plan',
        ),
        migrations.DeleteModel(
            name='Planes',
        ),
    ]
